#pragma once
enum Color{WHITE, BLACK};
enum PieceType{WHITE_PAWN,  WHITE_KNIGHT, WHITE_BISHOP, 
    WHITE_ROOK, WHITE_QUEEN, WHITE_KING, 
    BLACK_PAWN, BLACK_KNIGHT, BLACK_BISHOP, 
    BLACK_ROOK, BLACK_QUEEN, BLACK_KING, NONE};
enum CastleType{WHITE_QUEENSIDE, WHITE_KINGSIDE,
BLACK_QUEENSIDE, BLACK_KINGSIDE};